[PARQUET_DATA_LOADER_SETTINGS]
daily_stocks_dir = "D:\\stock_data\\daily_stock_prices"
daily_options_root_dir = "D:\\options_data"


[FIELD_MAPPING]
option_id = 'option_id'
symbol = 'symbol'
strike = 'strike'
expiration = 'expiration'
option_type = 'option_type'
quote_datetime = 'data_date'
spot_price = 'underlying_price'
bid = 'bid'
ask = 'ask'
delta = 'delta'
gamma = 'gamma'
theta = 'theta'
vega = 'vega'
open_interest = 'open_interest'
implied_volatility = 'iv'