name="BACKTRADER OPTIONS TESTING"

standard_fee=0.50
incur_fees=false
slippage=0.05
apply_slippage_entry=false
apply_slippage_exit=false
options_directory = 'D:\options_data'
data_fequency = 'intraday'
timeslot_filename_format = '%Y_%m_%d_%H_%M'



